<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="WTC-5159473-l2" name="USRC.USRC_General" tests="4" failures="1" timestamp="18 Oct 2019 14:06:37 GMT" time="20.005" errors="0">
  <testcase name="CreateUsers_User_Data" time="9.481" classname="USRC.USRC_General">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;successful\&quot;:true&quot;
     but: was &quot;{&quot;successful&quot;:false,&quot;errorList&quot;:[{&quot;code&quot;:&quot;USERID_TAKEN&quot;,&quot;message&quot;:&quot;This user ID has already been chosen by someone else. Please choose another user ID.&quot;,&quot;contextList&quot;:[&quot;SENDER&quot;],&quot;source&quot;:&quot;WIDM&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_General.CreateUsers_User_Data(USRC_General.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateUsers_User_Data -->
  <testcase name="CreateUsers_User_Data" time="10.524" classname="USRC.USRC_General"/>
  <testcase name="CreateUsers_AddressDetails" classname="USRC.USRC_General">
    <skipped/>
  </testcase> <!-- CreateUsers_AddressDetails -->
  <testcase name="CreateUsers" classname="USRC.USRC_General">
    <skipped/>
  </testcase> <!-- CreateUsers -->
</testsuite> <!-- USRC.USRC_General -->
