<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Test_Data_Generation.Test_Data_Generation" tests="80" failures="69" timestamp="14 Aug 2019 17:50:37 GMT" time="15562.342" errors="11">
  <testcase name="INET_Create_Shipment" time="111.339" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="189.065" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="50.237" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="254.912" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="98.535" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="64.605" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="193.306" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="231.505" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="155.327" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="177.945" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="180.626" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="38.734" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="115.516" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="57.289" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="285.571" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="268.623" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="163.420" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="290.249" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="112.382" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="144.981" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="101.221" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="351.982" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="162.315" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="124.705" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="367.549" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="44.622" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="272.819" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="336.888" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="135.519" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="142.700" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="102.626" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="36.458" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="92.410" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="136.861" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="63.927" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="104.936" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="89.163" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="60.663" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="63.591" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="179.810" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="234.706" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="323.655" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="156.907" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="208.229" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="89.026" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="214.942" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="227.030" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="177.760" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="200.265" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="2001.980" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="245.026" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="369.267" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="126.017" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="246.526" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="348.445" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="156.333" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="272.683" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="189.537" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="150.280" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="76.007" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="141.378" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="114.421" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="70.391" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="257.753" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="218.462" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="70.522" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="173.013" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="147.141" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="99.261" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="64.254" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="203.207" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="185.408" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="149.670" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="216.950" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="162.302" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="184.622" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="228.604" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="97.364" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="127.080" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status not found">
      <![CDATA[java.lang.AssertionError: Status not found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:126)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="480.986" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
</testsuite> <!-- Test_Data_Generation.Test_Data_Generation -->
