<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="WTC-5159473-l2" name="USRC_Application.USRC_FDM" tests="2" failures="1" timestamp="02 Jul 2019 14:00:29 GMT" time="10.469" errors="0">
  <testcase name="EndtoEndEnrollment" time="10.469" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;enrollmentOptionsList&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;a3eb5664-a417-455a-b9b7-82cd5a5f9db8&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;SYSTEM.UNEXPECTED.ERROR&quot;,&quot;message&quot;:&quot;The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "enrollmentOptionsList"
     but: was "{"transactionId":"a3eb5664-a417-455a-b9b7-82cd5a5f9db8","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:111)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment -->
  <testcase name="EndtoEndEnrollment_UserID" classname="USRC_Application.USRC_FDM">
    <skipped/>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- USRC_Application.USRC_FDM -->
