<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="WTC-5159473-l2" name="USRC_Application.USRC_TestData_Update" tests="6" failures="2" timestamp="05 Sep 2019 16:24:04 GMT" time="102.894" errors="0">
  <testcase name="CheckLogin" time="34.936" classname="USRC_Application.USRC_TestData_Update"/>
  <testcase name="CheckLogin" time="33.758" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:195)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckLogin" time="34.200" classname="USRC_Application.USRC_TestData_Update">
    <failure type="java.lang.AssertionError" message="Not able to login">
      <![CDATA[java.lang.AssertionError: Not able to login
at org.junit.Assert.fail(Assert.java:88)
at USRC_Application.USRC_TestData_Update.CheckLogin(USRC_TestData_Update.java:195)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CheckLogin -->
  <testcase name="CheckMigration" classname="USRC_Application.USRC_TestData_Update">
    <skipped/>
  </testcase> <!-- CheckMigration -->
  <testcase name="Check_WCRV_Status" classname="USRC_Application.USRC_TestData_Update">
    <skipped/>
  </testcase> <!-- Check_WCRV_Status -->
  <testcase name="UpdateUser" classname="USRC_Application.USRC_TestData_Update">
    <skipped/>
  </testcase> <!-- UpdateUser -->
</testsuite> <!-- USRC_Application.USRC_TestData_Update -->
