<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Test_Data_Generation.Tracking_Number_Generation" tests="1" failures="1" timestamp="01 Mar 2021 23:03:23 GMT" time="14.822" errors="0">
  <testcase name="SHPC_Create_Shipment" time="14.822" classname="Test_Data_Generation.Tracking_Number_Generation">
    <failure type="java.lang.AssertionError" message="Unable to create any shipments.">
      <![CDATA[java.lang.AssertionError: Unable to create any shipments.
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Number_Generation.SHPC_Create_Shipment(Tracking_Number_Generation.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- SHPC_Create_Shipment -->
</testsuite> <!-- Test_Data_Generation.Tracking_Number_Generation -->
