<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="Test_Data_Generation.Test_Data_Generation" tests="20" failures="11" timestamp="19 Aug 2019 15:39:09 GMT" time="6381.518" errors="6">
  <testcase name="INET_Create_Shipment" time="438.017" classname="Test_Data_Generation.Test_Data_Generation"/>
  <testcase name="INET_Create_Shipment" time="37.541" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="270.909" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="76.791" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="543.569" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="632.185" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="49.424" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="466.550" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="206.961" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="434.843" classname="Test_Data_Generation.Test_Data_Generation"/>
  <testcase name="INET_Create_Shipment" time="399.182" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="530.120" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="437.505" classname="Test_Data_Generation.Test_Data_Generation"/>
  <testcase name="INET_Create_Shipment" time="540.017" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="134.816" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="135.018" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="139.254" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="166.491" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="528.971" classname="Test_Data_Generation.Test_Data_Generation">
    <failure type="java.lang.AssertionError" message="Status_Not_Found">
      <![CDATA[java.lang.AssertionError: Status_Not_Found
at org.testng.Assert.fail(Assert.java:96)
at Test_Data_Generation.Tracking_Data_Update.Tracking_Number_Update(Tracking_Data_Update.java:138)
at INET_Application.INET_Shipment.INET_Create_Shipment(INET_Shipment.java:97)
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:80)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- INET_Create_Shipment -->
  <testcase name="INET_Create_Shipment" time="213.354" classname="Test_Data_Generation.Test_Data_Generation">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Test_Data_Generation.Test_Data_Generation.INET_Create_Shipment(Test_Data_Generation.java:83)
at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- INET_Create_Shipment -->
</testsuite> <!-- Test_Data_Generation.Test_Data_Generation -->
