<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="WTC-5159473-l2" name="USRC.USRC_FDM" tests="12" failures="2" timestamp="16 Oct 2019 14:01:22 GMT" time="921.677" errors="0">
  <testcase name="EndtoEndEnrollment" time="93.615" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="103.393" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="78.466" classname="USRC.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;enrollmentOptionsList&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;e177a69b-5a0b-45f6-bdcf-e45d4e409ab2&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;SYSTEM.UNEXPECTED.ERROR&quot;,&quot;message&quot;:&quot;The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "enrollmentOptionsList"
     but: was "{"transactionId":"e177a69b-5a0b-45f6-bdcf-e45d4e409ab2","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment -->
  <testcase name="EndtoEndEnrollment" time="87.539" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="96.525" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="102.639" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="103.021" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="97.015" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment" time="63.781" classname="USRC.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;successful\&quot;:true&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;6557216d-7374-4ab5-a80e-9e1cc327bedd&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;SYSTEM.UNEXPECTED.ERROR&quot;,&quot;message&quot;:&quot;The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"transactionId":"6557216d-7374-4ab5-a80e-9e1cc327bedd","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"The system has experienced an unexpected problem and is unable to complete your request.  Please try again later.  We regret any inconvenience."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment -->
  <testcase name="EndtoEndEnrollment" time="95.683" classname="USRC.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" classname="USRC.USRC_FDM">
    <skipped/>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment_UserID" classname="USRC.USRC_FDM">
    <skipped/>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- USRC.USRC_FDM -->
